version: '3'
services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    expose:
      - 5673
    ports:
      - "5673:5672"
    volumes:
      - rabbit:/var/lib/rabbit
      - ./rabbit.conf:/etc/rabbit/rabbitmq.conf
    env_file:
      - ./.env.rabbit
  celery:
    build: .
    command: celery -A kaztour_bot worker --pool=solo -l info
    volumes:
      - .:/kaztour_bot
    depends_on:
      - db
      - rabbit
    env_file:
      - ./.env.prod
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    ports:
      - "5433:5432"
#    logging:
#      driver: none
  web:
    build: .
    command: sh -c "/wait &&
      pip install -r requirements.txt &&
      python manage.py collectstatic --no-input --clear &&
      python manage.py createsuperuser --no-input || true &&
      gunicorn kaztour_bot.wsgi:application --bind 0.0.0.0:8000"
#      python manage.py runserver 0:8000"
    volumes:
      - .:/kaztour_bot
    ports:
      - "8000:8000"
#      - "8990:8990"
    depends_on:
      - db
      - rabbit
    links:
      - db
    env_file:
    - ./.env.prod

volumes:
  postgres_data:
  static_volume:
  media_volume:
  rabbit: