# Generated by Django 3.2 on 2021-04-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210423_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotText',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Приветствие (1-е сообщение)'), (2, 'Приветствие (2-е сообщение)'), (3, 'Приветствие (3-е сообщение)'), (4, 'Приветствие (4-е сообщение)'), (5, 'Вариант ответа 1 (после приветствия)'), (6, 'Вариант ответа 2 (после приветствия)'), (7, 'Текст о предложении отправить аудио'), (8, 'Текст о подтверждении текста с аудио'), (9, 'Вариант ответа 1 (подтверждение)'), (10, 'Вариант ответа 2 (опровержение)'), (11, 'Текст переотправки аудио'), (12, 'Текст о способе контакта (1-е сообщение)'), (13, 'Текст о способе контакта (2-е сообщение)'), (14, 'Вариант ответа 1 (звонок)'), (15, 'Вариант ответа 1 (WhatsApp)'), (16, 'Вариант ответа 1 (Telegram)'), (17, 'Текст об отправке номера телефона (шаблон)'), (18, 'Текст о некорректном номере телефона'), (19, 'Заключающее сообщение')], primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Текст бота',
                'verbose_name_plural': 'Текста бота',
                'ordering': ['my_order'],
            },
        ),
    ]
