# Generated by Django 3.2 on 2021-04-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bottext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottext',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
