# Generated by Django 3.2 on 2021-04-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bottext_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='current_sub_step',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Текущий подшаг'),
        ),
    ]
