# Generated by Django 3.2 on 2021-04-23 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_telegramuser_current_sub_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Надпись')),
            ],
            options={
                'verbose_name': 'Способ связи',
                'verbose_name_plural': 'Способы связи',
            },
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='with_own_option',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='is_own_option',
            field=models.BooleanField(default=False, verbose_name='Свой вариант'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='bottext',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Приветствие (1-е сообщение, должно содержать "{}" для вствки имени)'), (2, 'Приветствие (2-е сообщение)'), (3, 'Приветствие (3-е сообщение)'), (4, 'Приветствие (4-е сообщение)'), (5, 'Вариант ответа 1 (после приветствия)'), (6, 'Вариант ответа 2 (после приветствия)'), (7, 'Текст о предложении отправить аудио'), (8, 'Текст о подтверждении текста с аудио (должно содержать "{}" для вствки текста)'), (9, 'Вариант ответа 1 (подтверждение)'), (10, 'Вариант ответа 2 (опровержение)'), (11, 'Текст переотправки аудио'), (12, 'Текст о способе контакта (1-е сообщение, должно содержать "{}" для вствки имениК)'), (13, 'Текст о способе контакта (2-е сообщение)'), (14, 'Текст об отправке номера телефона (шаблон)'), (15, 'Текст о некорректном номере телефона'), (16, 'Заключающее сообщение'), (17, 'Текст ответа на некорректное сообщение')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.surveyquestion', verbose_name='Вопрос'),
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('audio_suggestion', models.TextField(blank=True, null=True, verbose_name='Переведенное аудио')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='main.telegramuser', verbose_name='Пользователь телеграм')),
            ],
            options={
                'verbose_name': 'Данные пользователя',
                'verbose_name_plural': 'Данные пользователя',
            },
        ),
    ]
