# Generated by Django 3.2 on 2021-05-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210424_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='text',
            new_name='answers',
        ),
        migrations.AddField(
            model_name='userdata',
            name='contact_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Способ контакта'),
        ),
    ]
