# Generated by Django 3.2 on 2021-07-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210504_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='answers',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
