# Generated by Django 3.2 on 2021-07-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_userdata_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacttype',
            options={'ordering': ['my_order'], 'verbose_name': 'Способ связи', 'verbose_name_plural': 'Способы связи'},
        ),
        migrations.AddField(
            model_name='contacttype',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
